name: Node Lint
run-name: Lint Nodejs app
on: [push]
jobs:
  Lint-Node-App:
    runs-on: [self-hosted]
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4
      - name: Configurar Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Instalar dependencias
        working-directory: ./calculadora
        run: |
          npm install
      - name: Ejecutar lint en el aplicativo
        working-directory: ./calculadora
        run: |
          npm run lint